[credentials]
  [credentials.usernames]

    [credentials.usernames.alice]
    email = "alice@example.com"
    name = "Alice Smith"
    password = "abc123"   # 🔑 plain for now, should be hashed later

    [credentials.usernames.bob]
    email = "bob@example.com"
    name = "Bob Jones"
    password = "def456"

    [credentials.usernames.roto]
    email = "robertemaillist@gmail.com"
    name = "roto"
    password = "chapter4"

[cookie]
name = "bookz_cookie"
key = "some_random_key_123"   # 🔑 change this to something long & random
expiry_days = 30
